name : Check Bat Version

on:
    push:
        branches:
          - devops
    workflow_dispatch:
jobs:
    check-bat-version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Node Js
              uses: actions/setup-node@v2
              with:
                node-version: 18
            - name: Install Bat
              run: npm install -g bats
            - name: Check Bat Version
              run: bats --version